#connection properties
connections:
  spark:
    ip: localhost
    port: 4040
  hive:
    ip: localhost
    port: 9090
  iceberg:
    ip: localhost
    port: 8080
# List of Analysis groups
groups:
  # Analysis group
  - id: 0
    database_scale_factor: 3
    table_formats: 
      hive:
        # list of tables' partitions
        partition: 
          # Table name: Partition By 
          lineitem_hive: receiptdate
      iceberg:
        merge_mode: merge-on-read
        update_mode: merge-on-read
        delete_mode: merge-on-read
        partition: 
          lineitem_ice: months(receiptdate)
